language: python
python: 2.7
env:
  - PLONE_VERSION=4.3
install:
  - virtualenv test-env --no-setuptools
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - test-env/bin/python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
script: bin/test
